=begin
#Knetik Platform API Documentation latest 

#This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for KnetikCloudClient::BRERuleEngineEventsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BRERuleEngineEventsApi' do
  before do
    # run before each test
    @instance = KnetikCloudClient::BRERuleEngineEventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BRERuleEngineEventsApi' do
    it 'should create an instact of BRERuleEngineEventsApi' do
      expect(@instance).to be_instance_of(KnetikCloudClient::BRERuleEngineEventsApi)
    end
  end

  # unit tests for send_bre_event
  # Fire a new event, based on an existing trigger
  # Parameters within the event must match names and types from the trigger. Actual rule execution is asynchornous.  Returns request id, which will be used as the event id
  # @param [Hash] opts the optional parameters
  # @option opts [BreEvent] :bre_event The BRE event object
  # @return [String]
  describe 'send_bre_event test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
