=begin
#Knetik Platform API Documentation Latest

#This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com

OpenAPI spec version: Latest
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::BRERuleEngineCategoriesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BRERuleEngineCategoriesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::BRERuleEngineCategoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BRERuleEngineCategoriesApi' do
    it 'should create an instact of BRERuleEngineCategoriesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::BRERuleEngineCategoriesApi)
    end
  end

  # unit tests for create_template_using_post1
  # Create a BRE category template
  # Templates define a type of BRE category and the properties they have
  # @param [Hash] opts the optional parameters
  # @option opts [TemplateResource] :template The category template to create
  # @return [TemplateResource]
  describe 'create_template_using_post1 test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_template_using_delete
  # Delete a BRE category template
  # If cascade &#x3D; &#39;detach&#39;, it will force delete the template even if it&#39;s attached to other objects
  # @param id The id of the template
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cascade The value needed to delete used templates
  # @return [nil]
  describe 'delete_template_using_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_categories_using_get
  # List categories
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :size The number of objects returned per page
  # @option opts [Integer] :page The number of the page returned, starting with 1
  # @return [PageResourceBreCategoryResource]
  describe 'get_categories_using_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_category_using_get
  # Get a single category
  # 
  # @param name The category name
  # @param [Hash] opts the optional parameters
  # @return [BreCategoryResource]
  describe 'get_category_using_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_template_using_get
  # Get a single BRE category template
  # 
  # @param id The id of the template
  # @param [Hash] opts the optional parameters
  # @return [TemplateResource]
  describe 'get_template_using_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_templates_using_get
  # List and search BRE category templates
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :size The number of objects returned per page
  # @option opts [Integer] :page The number of the page returned, starting with 1
  # @option opts [String] :order A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC]
  # @return [PageResourceTemplateResource]
  describe 'get_templates_using_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_category_using_put
  # Update a category
  # 
  # @param name The category name
  # @param [Hash] opts the optional parameters
  # @option opts [BreCategoryResource] :category The updated BRE category information
  # @return [nil]
  describe 'update_category_using_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_template_using_put1
  # Update a BRE category template
  # 
  # @param id The id of the template
  # @param [Hash] opts the optional parameters
  # @option opts [TemplateResource] :template The updated category template definition
  # @return [nil]
  describe 'update_template_using_put1 test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
