=begin
#Knetik Platform API Documentation latest 

#This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for KnetikCloudClient::BRERuleEngineVariablesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BRERuleEngineVariablesApi' do
  before do
    # run before each test
    @instance = KnetikCloudClient::BRERuleEngineVariablesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BRERuleEngineVariablesApi' do
    it 'should create an instact of BRERuleEngineVariablesApi' do
      expect(@instance).to be_instance_of(KnetikCloudClient::BRERuleEngineVariablesApi)
    end
  end

  # unit tests for get_bre_variable_types
  # Get a list of variable types available
  # Types include integer, string, user and invoice. These are used to qualify trigger parameters and action variables with strong typing.
  # @param [Hash] opts the optional parameters
  # @return [Array<VariableTypeResource>]
  describe 'get_bre_variable_types test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
