=begin
#Knetik Platform API Documentation latest 

#This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for KnetikCloudClient::CurrenciesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CurrenciesApi' do
  before do
    # run before each test
    @instance = KnetikCloudClient::CurrenciesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CurrenciesApi' do
    it 'should create an instance of CurrenciesApi' do
      expect(@instance).to be_instance_of(KnetikCloudClient::CurrenciesApi)
    end
  end

  # unit tests for create_currency
  # Create a currency
  # &lt;b&gt;Permissions Needed:&lt;/b&gt; CURRENCIES_ADMIN
  # @param [Hash] opts the optional parameters
  # @option opts [CurrencyResource] :currency The currency object
  # @return [CurrencyResource]
  describe 'create_currency test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_currency
  # Delete a currency
  # &lt;b&gt;Permissions Needed:&lt;/b&gt; CURRENCIES_ADMIN
  # @param code The currency code
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_currency test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_currencies
  # List and search currencies
  # &lt;b&gt;Permissions Needed:&lt;/b&gt; ANY
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :filter_default Filter for the one currency that is set as default (true), or all that are not (false)
  # @option opts [BOOLEAN] :filter_enabled_currencies Filter for alternate currencies setup explicitely in system config
  # @option opts [String] :filter_type Filter currencies by type.  Allowable values: (&#39;virtual&#39;, &#39;real&#39;)
  # @option opts [Integer] :size The number of objects returned per page
  # @option opts [Integer] :page The number of the page returned, starting with 1
  # @option opts [String] :order A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC]
  # @return [PageResourceCurrencyResource]
  describe 'get_currencies test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_currency
  # Get a single currency
  # &lt;b&gt;Permissions Needed:&lt;/b&gt; ANY
  # @param code The currency code
  # @param [Hash] opts the optional parameters
  # @return [CurrencyResource]
  describe 'get_currency test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_currency
  # Update a currency
  # &lt;b&gt;Permissions Needed:&lt;/b&gt; CURRENCIES_ADMIN
  # @param code The currency code
  # @param [Hash] opts the optional parameters
  # @option opts [CurrencyResource] :currency The currency object
  # @return [nil]
  describe 'update_currency test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
