=begin
#Knetik Platform API Documentation latest 

#This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for KnetikCloudClient::GamificationLeaderboardsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GamificationLeaderboardsApi' do
  before do
    # run before each test
    @instance = KnetikCloudClient::GamificationLeaderboardsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GamificationLeaderboardsApi' do
    it 'should create an instance of GamificationLeaderboardsApi' do
      expect(@instance).to be_instance_of(KnetikCloudClient::GamificationLeaderboardsApi)
    end
  end

  # unit tests for get_leaderboard
  # Retrieves leaderboard details and paginated entries
  # The context type identifies the type of entity (i.e., &#39;activity&#39;) being tracked on the leaderboard. The context ID is the unique ID of the actual entity tracked by the leaderboard. Sorting is based on the fields of LeaderboardEntryResource rather than the returned LeaderboardResource. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; ANY
  # @param context_type The context type for the leaderboard
  # @param context_id The context id for the leaderboard
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :size The number of objects returned per page
  # @option opts [Integer] :page The number of the page returned, starting with 1
  # @option opts [String] :order A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC]
  # @return [LeaderboardResource]
  describe 'get_leaderboard test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_leaderboard_rank
  # Retrieves a specific user entry with rank
  # The context type identifies the type of entity (i.e., &#39;activity&#39;) being tracked on the leaderboard. The context ID is the unique ID of the actual entity tracked by the leaderboard. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; ANY
  # @param context_type The context type for the leaderboard
  # @param context_id The context id for the leaderboard
  # @param id The id of a user
  # @param [Hash] opts the optional parameters
  # @return [LeaderboardEntryResource]
  describe 'get_leaderboard_rank test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_leaderboard_strategies
  # Get a list of available leaderboard strategy names
  # &lt;b&gt;Permissions Needed:&lt;/b&gt; ANY
  # @param [Hash] opts the optional parameters
  # @return [Array<String>]
  describe 'get_leaderboard_strategies test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
