=begin
#Knetik Platform API Documentation Latest

#This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com

OpenAPI spec version: Latest
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::LogsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LogsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::LogsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LogsApi' do
    it 'should create an instact of LogsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::LogsApi)
    end
  end

  # unit tests for add_user_log_using_post
  # Add a new user log entry
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [UserActionLog] :log_entry The user log entry to be added
  # @return [nil]
  describe 'add_user_log_using_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_log_using_get
  # Get an existing BRE event log entry by id
  # 
  # @param id The BRE event log entry id
  # @param [Hash] opts the optional parameters
  # @return [BreEventLog]
  describe 'get_event_log_using_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_events_logs_using_get
  # Returns a list of BRE event log entries
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter_start_date A comma separated string without spaces.  First value is the operator to search on, second value is the event log start date, a unix timestamp in seconds.  Allowed operators: (GT, LT, EQ, GOE, LOE).
  # @option opts [String] :filter_event_name Filter event logs by event name
  # @option opts [Integer] :size The number of objects returned per page
  # @option opts [Integer] :page The number of the page returned, starting with 1
  # @option opts [String] :order A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC]
  # @return [PageResourceBreEventLog]
  describe 'get_events_logs_using_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_forward_log_using_get
  # Get an existing forward log entry by id
  # 
  # @param id The forward log entry id
  # @param [Hash] opts the optional parameters
  # @return [ForwardLog]
  describe 'get_forward_log_using_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_forward_logs_using_get
  # Returns a list of forward log entries
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter_start_date A comma separated string without spaces.  First value is the operator to search on, second value is the log start date, a unix timestamp in seconds.  Allowed operators: (GT, LT, EQ, GOE, LOE).
  # @option opts [String] :filter_end_date A comma separated string without spaces.  First value is the operator to search on, second value is the log end date, a unix timestamp in seconds.  Allowed operators: (GT, LT, EQ, GOE, LOE).
  # @option opts [Integer] :filter_status_code Filter forward logs by http status code
  # @option opts [Integer] :size The number of objects returned per page
  # @option opts [Integer] :page The number of the page returned, starting with 1
  # @option opts [String] :order A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC]
  # @return [PageResourceForwardLog]
  describe 'get_forward_logs_using_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_logs_using_get
  # Returns a user log entry by id
  # 
  # @param id The user log entry id
  # @param [Hash] opts the optional parameters
  # @return [UserActionLog]
  describe 'get_user_logs_using_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_logs_using_get1
  # Returns a page of user logs entries
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :filter_user Filter for actions taken by a specific user by id
  # @option opts [String] :filter_action_name Filter for actions of a specific name
  # @option opts [Integer] :size The number of objects returned per page
  # @option opts [Integer] :page The number of the page returned, starting with 1
  # @return [PageResourceUserActionLog]
  describe 'get_user_logs_using_get1 test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
