=begin
#Knetik Platform API Documentation latest 

#This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for KnetikCloudClient::PaymentsAppleApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PaymentsAppleApi' do
  before do
    # run before each test
    @instance = KnetikCloudClient::PaymentsAppleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentsAppleApi' do
    it 'should create an instance of PaymentsAppleApi' do
      expect(@instance).to be_instance_of(KnetikCloudClient::PaymentsAppleApi)
    end
  end

  # unit tests for verify_apple_receipt
  # Pay invoice with Apple receipt
  # Mark an invoice paid using Apple payment receipt. A receipt will only be accepted once and the details of the transaction must match the invoice, including the product_id matching the sku text of the item in the invoice. Returns the transaction ID if successful.
  # @param [Hash] opts the optional parameters
  # @option opts [ApplyPaymentRequest] :request The request for paying an invoice through an Apple receipt
  # @return [String]
  describe 'verify_apple_receipt test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
