=begin
#Knetik Platform API Documentation latest 

#This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for KnetikCloudClient::PaymentsPayPalClassicApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PaymentsPayPalClassicApi' do
  before do
    # run before each test
    @instance = KnetikCloudClient::PaymentsPayPalClassicApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentsPayPalClassicApi' do
    it 'should create an instance of PaymentsPayPalClassicApi' do
      expect(@instance).to be_instance_of(KnetikCloudClient::PaymentsPayPalClassicApi)
    end
  end

  # unit tests for create_pay_pal_billing_agreement_url
  # Create a PayPal Classic billing agreement for the user
  # Returns the token that should be used to forward the user to PayPal so they can accept the agreement.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateBillingAgreementRequest] :request The request to create a PayPal billing agreement
  # @return [String]
  describe 'create_pay_pal_billing_agreement_url test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_pay_pal_express_checkout
  # Create a payment token for PayPal express checkout
  # Returns the token that should be used to forward the user to PayPal so they can complete the checkout.
  # @param [Hash] opts the optional parameters
  # @option opts [CreatePayPalPaymentRequest] :request The request to create a PayPal payment token
  # @return [String]
  describe 'create_pay_pal_express_checkout test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for finalize_pay_pal_billing_agreement
  # Finalizes a billing agreement after the user has accepted through PayPal
  # Returns the ID of the new payment method created for the user for the billing agreement.
  # @param [Hash] opts the optional parameters
  # @option opts [FinalizeBillingAgreementRequest] :request The request to finalize a PayPal billing agreement
  # @return [Integer]
  describe 'finalize_pay_pal_billing_agreement test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for finalize_pay_pal_checkout
  # Finalizes a payment after the user has completed checkout with PayPal
  # The invoice will be marked paid/failed by asynchronous IPN callback.
  # @param [Hash] opts the optional parameters
  # @option opts [FinalizePayPalPaymentRequest] :request The request to finalize the payment
  # @return [nil]
  describe 'finalize_pay_pal_checkout test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
