=begin
#Knetik Platform API Documentation Latest

#This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com

OpenAPI spec version: Latest
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SwaggerClient

  class ChallengeResource
    # The number of activities allowed to this challenge
    attr_accessor :activities

    # A map of additional properties, keyed on the property name.  Must match the names and types defined in the template for this item type
    attr_accessor :additional_properties

    # The id of the campaign this challenge is a part of. The challenge must be tied to an active campaign before it will spawn events
    attr_accessor :campaign_id

    # The ID of the original challenge it was copied from
    attr_accessor :copy_of

    # The date/time this resource was created in seconds since unix epoch
    attr_accessor :created_date

    # The end date of this challenge in seconds since epoch. required if part of a campaign
    attr_accessor :end_date

    # The unique ID for that resource
    attr_accessor :id

    # The strategy for calculating the leaderboard. Defaults to highest score. Value MUST come from the list of available strategies from the Leaderboard Service.
    attr_accessor :leaderboard_strategy

    # The user friendly name of that resource. Defaults to blank string
    attr_accessor :long_description

    # The user friendly name of that resource
    attr_accessor :name

    # The next date this challenge will be occur in seconds since epoch
    attr_accessor :next_event_date

    # The number of minutes minimum to wait at the end of this challenge before running rewards, to allow activities to complete
    attr_accessor :reward_lag_minutes

    # The rewards to give at the end of the challenge. When creating/updating only id is used. Reward set must be pre-existing
    attr_accessor :reward_set

    # The repeat schedule for the challenge
    attr_accessor :schedule

    # The user friendly name of that resource. Defaults to blank string
    attr_accessor :short_description

    # The start date of this challenge in seconds since epoch. required if part of a campaign
    attr_accessor :start_date

    # A challenge template this challenge is validated against (private). May be null and no validation of additional_properties will be done
    attr_accessor :template

    # The date/time this resource was last updated in seconds since unix epoch
    attr_accessor :updated_date


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'activities' => :'activities',
        :'additional_properties' => :'additional_properties',
        :'campaign_id' => :'campaign_id',
        :'copy_of' => :'copy_of',
        :'created_date' => :'created_date',
        :'end_date' => :'end_date',
        :'id' => :'id',
        :'leaderboard_strategy' => :'leaderboard_strategy',
        :'long_description' => :'long_description',
        :'name' => :'name',
        :'next_event_date' => :'next_event_date',
        :'reward_lag_minutes' => :'reward_lag_minutes',
        :'reward_set' => :'reward_set',
        :'schedule' => :'schedule',
        :'short_description' => :'short_description',
        :'start_date' => :'start_date',
        :'template' => :'template',
        :'updated_date' => :'updated_date'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'activities' => :'Integer',
        :'additional_properties' => :'Hash<String, Property>',
        :'campaign_id' => :'Integer',
        :'copy_of' => :'Integer',
        :'created_date' => :'Integer',
        :'end_date' => :'Integer',
        :'id' => :'Integer',
        :'leaderboard_strategy' => :'String',
        :'long_description' => :'String',
        :'name' => :'String',
        :'next_event_date' => :'Integer',
        :'reward_lag_minutes' => :'Integer',
        :'reward_set' => :'RewardSetResource',
        :'schedule' => :'Schedule',
        :'short_description' => :'String',
        :'start_date' => :'Integer',
        :'template' => :'String',
        :'updated_date' => :'Integer'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'activities')
        self.activities = attributes[:'activities']
      end

      if attributes.has_key?(:'additional_properties')
        if (value = attributes[:'additional_properties']).is_a?(Array)
          self.additional_properties = value
        end
      end

      if attributes.has_key?(:'campaign_id')
        self.campaign_id = attributes[:'campaign_id']
      end

      if attributes.has_key?(:'copy_of')
        self.copy_of = attributes[:'copy_of']
      end

      if attributes.has_key?(:'created_date')
        self.created_date = attributes[:'created_date']
      end

      if attributes.has_key?(:'end_date')
        self.end_date = attributes[:'end_date']
      end

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'leaderboard_strategy')
        self.leaderboard_strategy = attributes[:'leaderboard_strategy']
      end

      if attributes.has_key?(:'long_description')
        self.long_description = attributes[:'long_description']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'next_event_date')
        self.next_event_date = attributes[:'next_event_date']
      end

      if attributes.has_key?(:'reward_lag_minutes')
        self.reward_lag_minutes = attributes[:'reward_lag_minutes']
      end

      if attributes.has_key?(:'reward_set')
        self.reward_set = attributes[:'reward_set']
      end

      if attributes.has_key?(:'schedule')
        self.schedule = attributes[:'schedule']
      end

      if attributes.has_key?(:'short_description')
        self.short_description = attributes[:'short_description']
      end

      if attributes.has_key?(:'start_date')
        self.start_date = attributes[:'start_date']
      end

      if attributes.has_key?(:'template')
        self.template = attributes[:'template']
      end

      if attributes.has_key?(:'updated_date')
        self.updated_date = attributes[:'updated_date']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push("invalid value for 'name', name cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @name.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          activities == o.activities &&
          additional_properties == o.additional_properties &&
          campaign_id == o.campaign_id &&
          copy_of == o.copy_of &&
          created_date == o.created_date &&
          end_date == o.end_date &&
          id == o.id &&
          leaderboard_strategy == o.leaderboard_strategy &&
          long_description == o.long_description &&
          name == o.name &&
          next_event_date == o.next_event_date &&
          reward_lag_minutes == o.reward_lag_minutes &&
          reward_set == o.reward_set &&
          schedule == o.schedule &&
          short_description == o.short_description &&
          start_date == o.start_date &&
          template == o.template &&
          updated_date == o.updated_date
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [activities, additional_properties, campaign_id, copy_of, created_date, end_date, id, leaderboard_strategy, long_description, name, next_event_date, reward_lag_minutes, reward_set, schedule, short_description, start_date, template, updated_date].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
