=begin
#Knetik Platform API Documentation latest 

#This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require "uri"

module KnetikCloudClient
  class UtilBatchApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Request to run API call given the method, content type, path url, and body of request
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Batch] :batch The batch object
    # @return [Array<BatchReturn>]
    def send_batch(opts = {})
      data, _status_code, _headers = send_batch_with_http_info(opts)
      return data
    end

    # Request to run API call given the method, content type, path url, and body of request
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Batch] :batch The batch object
    # @return [Array<(Array<BatchReturn>, Fixnum, Hash)>] Array<BatchReturn> data, response status code and response headers
    def send_batch_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: UtilBatchApi.send_batch ..."
      end
      # resource path
      local_var_path = "/batch"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'batch'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<BatchReturn>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: UtilBatchApi#send_batch\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
